AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Prefix:
    Type: String
    Description: Insert your name

Globals:
  Function:
    Tags:
      cmd:environment: 'test'
      cmd:app: 'sam'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Prefix}HelloWorld"
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 3
      Environment:
        Variables:
          PREFIX: !Ref Prefix

Outputs:
  HelloWorldFunctionArn:
    Description: "Arn of the Hello World function"
    Value: !GetAtt HelloWorldFunction.Arn

